language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

  # be nice and limit workload; queued commits older than this value will not be built
git:
  depth: 5

# currently all doc is done with Markdown  
latex: false

# we don't have any (important) reverse dependencies
r_check_revdep: false

r_packages:
  - roxygen2
  - covr
  
before_script:
  - Rscript -e 'Rcpp::compileAttributes()'
  - Rscript -e 'devtools::document()' 

after_success:
  - Rscript -e 'library(covr);codecov()' 
