# =======
# patching corner
# =======

# data.tree does not provide a find function as flexible as this one

Find <- function(node, value, field="name", traversal = c("pre-order", "post-order", "in-order", "level",
                                     "ancestor"), all = F){

  trav <- data.tree::Traverse(node, traversal, pruneFun = NULL, filterFun = NULL)
  ret <- trav[sapply(trav,function(x) any(x[[field]] == value))]

  if (length(ret) == 0) return(NULL)
  if (!all) return(ret[[1]])
  return(ret)

}

#' this expects a traversal and returns only the first match, behaves closely to data.tree::FindNode
#' trav <- Traverse(node, traversal, pruneFun = NULL, filterFun = NULL)
#'
#' @param trav a traversal generated by data.tree::Traverse
#' @param name the name of the node to search for
FindFirstFast <- function(trav, name){
  ret <- NULL
  for (x in trav) {
    if (x$name == name) {
      ret <- x
      break
    }
  }
  return(ret)
}
