# ====================
# The VCDFile Object and Related Objects (the interface stuff)
# ====================

#' VCD2R -- Loading Value Change Dumps int R.
#'
#' TODO: Package doc.
NULL

#' Create an VCDFileObject
#'
#' @param file The file to open.
#' @param parseHeader A flag whether the header should be parsed on opening the file. Default is TRUE.
#' @return An VCDFileObject containing information on \code{file}.
#' @examples
#' VCDFile()
#' VCDFile("inter.vcd")
#' VCDFile("inter.vcd",F)

VCDFile <- function(filename = NA_character_,parseHeader = T)
{
  vcd <- list(
    filename  = filename,
    date      = NA,
    timescale = NA_integer_,
    dumpstart = 0, # keep a rough track of where this part starts, so we can fast-forward to it at later parsing
    variables = NA
  )

  if (!is.na(filename)) {
    if (!file.exists(filename)) {
      warning("File does not exist: ", filename)
      vcd$filename = NA_character_
    } else {
      if (parseHeader) {
        parseResult <- parseVCDHeader(vcd)
        vcd$date <- parseResult$date
        vcd$version <- parseResult$version
        vcd$timescale <- parseResult$timescale
        vcd$dumpstart <- parseResult$dumpstart
        vcd$variables <- parseResult$variables
      }
    }
  }

  ## Set the name for the class
  class(vcd) <- append(class(vcd),"VCDFile")
  return(vcd)
}


# =========================
# pretty printing function for VCDFile
# =========================

print.VCDFile <- function(x, printVars = F) {
  writeLines(paste0("file: ",x$filename))
  writeLines(paste0("generated by: ",x$version))
  writeLines(paste0("dump recorded on ",x$date))
  writeLines(paste0("timescale: ",paste0(x$timescale,collapse=" ")))
  writeLines(paste0("number of signals: ",NA))
  # TODO print Metadata
  if (printVars)
    NULL # TODO print variable tree
  invisible(x)
}
